# Generated by Django 5.2.6 on 2025-09-23 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3621d3e-602a-4740-9ba6-cecf79d43607'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3621d3e-602a-4740-9ba6-cecf79d43607'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7cae5df-8c38-4adc-ba8b-f599fc0baa3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Household', 'Household'), ('sme', 'Sme'), ('Council', 'Council'), ('Recycler', 'Recycler')], default='Household', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3621d3e-602a-4740-9ba6-cecf79d43607'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('availabe', 'Availabe'), ('busy', 'Busy'), ('offline', 'Offline')], default='availabe', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3621d3e-602a-4740-9ba6-cecf79d43607'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89438b0b-bf4b-424d-8b3b-74d2c7cf51dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
