# Generated by Django 5.2.6 on 2025-09-23 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_collection_id_alter_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f98060e-ee9a-43f7-af1c-baacf3093e7a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f98060e-ee9a-43f7-af1c-baacf3093e7a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ba12ea9-ceba-4557-bc95-d130a96567d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Household', 'Household'), ('sme', 'Sme'), ('Council', 'Council'), ('Recycler', 'Recycler')], default='Household', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f98060e-ee9a-43f7-af1c-baacf3093e7a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('availabe', 'Availabe'), ('busy', 'Busy'), ('offline', 'Offline')], default='availabe', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f98060e-ee9a-43f7-af1c-baacf3093e7a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0796d753-cd3c-414c-9eba-9e74bce2dcf0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
