# Generated by Django 5.2.6 on 2025-09-25 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('facbacde-8277-481e-a9da-65016af04479'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='id',
            field=models.UUIDField(default=uuid.UUID('facbacde-8277-481e-a9da-65016af04479'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Household', 'Household'), ('sme', 'Sme'), ('Council', 'Council'), ('Recycler', 'Recycler')], default='Household', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('facbacde-8277-481e-a9da-65016af04479'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('availabe', 'Availabe'), ('busy', 'Busy'), ('offline', 'Offline')], default='availabe', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('facbacde-8277-481e-a9da-65016af04479'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('423b1302-ea7b-41de-b355-a2f721c17288'), editable=False, primary_key=True, serialize=False),
        ),
    ]
