# Generated by Django 5.2.6 on 2025-09-25 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b196b892-d5d5-4d9c-9fcb-b0554de81d18'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b196b892-d5d5-4d9c-9fcb-b0554de81d18'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Household', 'Household'), ('sme', 'Sme'), ('Council', 'Council'), ('Recycler', 'Recycler')], default='Household', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b196b892-d5d5-4d9c-9fcb-b0554de81d18'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('availabe', 'Availabe'), ('busy', 'Busy'), ('offline', 'Offline')], default='availabe', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b196b892-d5d5-4d9c-9fcb-b0554de81d18'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6316dd55-a89c-4851-95a0-23f1b8df9fb6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
