# Generated by Django 5.2.4 on 2025-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_latitude_booking_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
